-- Seed customers and invoices from existing orders data
-- This script extracts unique customers from orders and creates customer records
-- It also links existing orders to customers and creates sample invoices

-- Step 1: Insert unique customers from orders table
-- Extract unique customers based on email (primary key)
INSERT INTO customers (name, email, phone, status, created_at)
SELECT DISTINCT ON (LOWER(TRIM(client_email)))
  TRIM(client_name) as name,
  LOWER(TRIM(client_email)) as email,
  CASE 
    WHEN client_phone IS NOT NULL AND TRIM(client_phone) != '' THEN TRIM(client_phone)
    ELSE NULL
  END as phone,
  'active' as status,
  MIN(created_at) as created_at
FROM orders
WHERE client_email IS NOT NULL 
  AND TRIM(client_email) != ''
  AND LOWER(TRIM(client_email)) NOT IN (
    SELECT LOWER(TRIM(email)) FROM customers WHERE email IS NOT NULL
  )
GROUP BY LOWER(TRIM(client_email)), TRIM(client_name), client_phone
ON CONFLICT (email) DO NOTHING;

-- Step 2: Update orders table to link to customers
UPDATE orders o
SET customer_id = c.id
FROM customers c
WHERE LOWER(TRIM(o.client_email)) = LOWER(TRIM(c.email))
  AND o.customer_id IS NULL;

-- Step 3: Create invoices for completed and in_progress orders
-- Generate invoices for orders that don't have invoices yet
-- Note: invoice_number will be auto-generated by the trigger
INSERT INTO invoices (
  customer_id,
  order_id,
  issue_date,
  due_date,
  status,
  subtotal,
  tax_rate,
  currency,
  notes,
  invoice_number
)
SELECT 
  o.customer_id,
  o.id as order_id,
  COALESCE(
    (SELECT MAX(event_date::date) FROM tracking_events WHERE order_id = o.id),
    o.created_at::date
  ) as issue_date,
  (COALESCE(
    (SELECT MAX(event_date::date) FROM tracking_events WHERE order_id = o.id),
    o.created_at::date
  ) + INTERVAL '30 days')::date as due_date,
  CASE 
    WHEN o.status = 'completed' THEN 'sent'
    WHEN o.status = 'in_progress' THEN 'draft'
    ELSE 'draft'
  END as status,
  COALESCE(CAST(o.value AS DECIMAL(10,2)), 0) as subtotal,
  21.0 as tax_rate, -- TVA par défaut à 21%
  'EUR' as currency,
  'Facture générée automatiquement depuis la commande ' || o.order_number as notes,
  NULL as invoice_number -- Laisser le trigger générer le numéro automatiquement
FROM orders o
WHERE o.customer_id IS NOT NULL
  AND o.status IN ('completed', 'in_progress', 'confirmed')
  AND o.value IS NOT NULL
  AND CAST(o.value AS DECIMAL(10,2)) > 0
  AND NOT EXISTS (
    SELECT 1 FROM invoices i WHERE i.order_id = o.id
  )
ORDER BY o.created_at DESC
LIMIT 50; -- Limiter à 50 factures pour éviter de surcharger

-- Step 4: Mark some invoices as paid if orders are completed and older than 30 days
UPDATE invoices i
SET 
  status = 'paid',
  payment_date = i.due_date,
  payment_method = 'virement'
FROM orders o
WHERE i.order_id = o.id
  AND o.status = 'completed'
  AND i.status = 'sent'
  AND i.issue_date < CURRENT_DATE - INTERVAL '30 days'
  AND i.payment_date IS NULL;

-- Step 5: Mark overdue invoices
UPDATE invoices
SET status = 'overdue'
WHERE status = 'sent'
  AND due_date < CURRENT_DATE
  AND payment_date IS NULL;

-- Display summary
DO $$
DECLARE
  customer_count INTEGER;
  invoice_count INTEGER;
  linked_orders_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO customer_count FROM customers;
  SELECT COUNT(*) INTO invoice_count FROM invoices;
  SELECT COUNT(*) INTO linked_orders_count FROM orders WHERE customer_id IS NOT NULL;
  
  RAISE NOTICE 'Migration completed:';
  RAISE NOTICE '  - % customers created/linked', customer_count;
  RAISE NOTICE '  - % orders linked to customers', linked_orders_count;
  RAISE NOTICE '  - % invoices created', invoice_count;
END $$;

